name: Android Build

on:
  push:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull pre-built Docker image
        run: docker pull ghcr.io/${{ github.repository }}/android-dependencies:latest

      - name: Build app using pre-built image
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace \
          -w /workspace ghcr.io/${{ github.repository }}/android-dependencies:latest ./gradlew build
