name: Android Build

on:
  push:

# Can be separated in two workflows and then use:
#on:
#  workflow_run:
#    workflows: ["Build and Push Docker Image"]
#    types:
#    - completed
# But for that the workflow files need to be in the default branch, or at least the first workflow.
# When project escalates we can separate the jobs in two different workflows, adding at least the first of them to the default branch.
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            docker_triggers:
              - 'Dockerfile'

      - name: Log in to GitHub Container Registry
        if: steps.changes.docker_triggers == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository name to lowercase
        if: steps.changes.docker_triggers == 'true'
        id: repo_name
        run: echo "repo_lowercase=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build Docker image
        if: steps.changes.docker_triggers == 'true'
        run: docker build -t ghcr.io/${{ env.repo_lowercase }}/android-dependencies:latest .

      - name: Push Docker image
        if: steps.changes.docker_triggers == 'true'
        run: docker push ghcr.io/${{ env.repo_lowercase }}/android-dependencies:latest


  build-release:
    needs: build-and-push
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ignaciogarcia198/rickandmortycharacters/android-dependencies:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Decode the keystore and write key.properties
      - name: Setup signing configuration
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 -d > release.keystore
          cat <<EOF > key.properties
          rickAndMortyKeyAlias=${{ secrets.RELEASE_KEY_ALIAS }}
          rickAndMortyKeyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}
          rickAndMortyStoreFile=$GITHUB_WORKSPACE/release.keystore
          rickAndMortyStorePassword=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          EOF

      - name: Debug file paths
        run: |
          echo "current path:"
          pwd
          echo "github workspace:"
          echo $GITHUB_WORKSPACE
          echo "Key.properties:"
          cat key.properties

      # Build the APK
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Upload the release APK
      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk
