name: Build and Push Docker Image

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            docker_triggers:
              - 'Dockerfile'

      - name: Log in to GitHub Container Registry
        if: steps.changes.docker_triggers == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository name to lowercase
        if: steps.changes.docker_triggers == 'true'
        id: repo_name
        run: echo "repo_lowercase=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build Docker image
        if: steps.changes.docker_triggers == 'true'
        run: docker build -t ghcr.io/${{ env.repo_lowercase }}/android-dependencies:latest .

      - name: Push Docker image
        if: steps.changes.docker_triggers == 'true'
        run: docker push ghcr.io/${{ env.repo_lowercase }}/android-dependencies:latest
